site_name: grapes
repo_url: https://github.com/giuliofoletto/grapes
repo_name: giuliofoletto/grapes
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - grapes
          options:
            show_source: true
            show_submodules: true
            heading_level: 2
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api.md
  - Additional Remarks: remarks.md