site_name: grapes
repo_url: https://github.com/giuliofoletto/grapes
repo_name: giuliofoletto/grapes
site_url: https://giuliofolettograpes.readthedocs.io
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom
  logo: assets/logo.svg
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/custom.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - grapes
          options:
            show_source: true
            show_submodules: true
            heading_level: 2
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api.md
  - Additional Remarks: remarks.md